name: automerge
on:
  pull_request_review:
    types:
    - opened

  schedule:
    - cron: "10 22 * * *"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_FORKS: "true"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: "✨ Solved, automerge"
